name: "@minions-repos/blog"
project_scope: child
child_type: blog
parent_project: minions-repos-workspace
description: "Standard compliance definition for @minions-repos/blog"
priority: high
deploy_url: null
tags: null
category: minion-toolbox
